prometheus-blackbox-exporter:
    config:
        modules:
            http_auth_prometheus:
                http:
                    basic_auth:
                        password: ENC[AES256_GCM,data:lZSE+OiQ+zWJdG3r1g==,iv:VHUnp7D270U4HJtVz2sWhB4ZHFQy1OzTmc+3E9ShaPo=,tag:3Sti8Z15B4JMBNCq/MoO9Q==,type:str]
                        username: ENC[AES256_GCM,data:AWPOJFO7k+3mFA==,iv:cUnfsVSV+t9uks02t4zd9PMa+dHzV+A6OlJSMXp9roY=,tag:LO6HNfAwW9J7No2YP+aKIw==,type:str]
kube-prometheus-stack:
    alertmanager:
        config:
            global:
                slack_api_url: ENC[AES256_GCM,data:EeW6M832I93EaprZSrvBN2hmINhDBfOgQJ64S2KcabHvZRpM45h93QWWD8bgtdnELlb6e3mlIa/ec6ZsiO0HNDxt8YUxa2z9C6A6TP+xpQ==,iv:pEQH9V7jzEhu1FPcE//6AmPtxD1h4Tck15GEooiCaHg=,tag:4rBXiuXuLMj0+2lrCyr6oQ==,type:str]
            receivers:
                - name: ENC[AES256_GCM,data:F4j4ZrBtxkFxniBz6l4=,iv:+6X3aJbPZFvtknDUY/cynDtzJfPatbSKirDzrUZMX2o=,tag:OJ8HTQ80dXD4K/lLfLb1UQ==,type:str]
                  webhook_configs:
                    - url: ENC[AES256_GCM,data:1Sd2J5iLuMXRZQDgMo7k4+vOZxuxMs0j8k+BlDAD/gHO4kM6RCwQoku5J8ZopwU6k4JGrspFGMtwi4NLSyJBR5Qv2eSvHgJc1/AmMLD6nCHufDr+UngIKRUZ5KWtdca1mewkGPE/u6SunMjiAMyAfLd4ng==,iv:WywDQBulmgjIb570l+FKKa6naghowciACOuSOfWXrKI=,tag:KlnG4iF6Wk1Yw9d2BB7nEw==,type:str]
                      send_resolved: ENC[AES256_GCM,data:fauH3A==,iv:STlu75PHK+AB6ahcueSETLaMDVfNb2WruhHyUlpJhJs=,tag:TKhLdWTD0DaqgM2Bse9ZrQ==,type:bool]
                - name: ENC[AES256_GCM,data:Em/duw==,iv:cn4f8b4N2s8YLoRUbTLDCItKXs91Uqs/51Uf+DybPy8=,tag:RpL9PF6yPmSm8+olXLvhOQ==,type:str]
                - name: ENC[AES256_GCM,data:aPTWtMu6tay9bHvZ+kg5R0QNfQ==,iv:5MepP2OFcq6QsSaGtnW0eKW3ZFI9UNfHZBNzxBosSMQ=,tag:Ahq/ut6f3kYbGcpM7g+FMQ==,type:str]
                  slack_configs:
                    - channel: ENC[AES256_GCM,data:3Pj3ypiprRRdKV9zug==,iv:NbNTJ4pAKmpZP+R543lzKkHlAot2tnxy5f5qAbnf1WQ=,tag:kg4eLBneJTHjlrXBMha+lA==,type:str]
                      send_resolved: ENC[AES256_GCM,data:f/zlAA==,iv:aMLwINFz1VsVLEbiKYs4eJGPt/eKVm3P96Ach1s+0+c=,tag:qR7cBCNXca7i3G49wDqUrQ==,type:bool]
                      text: ENC[AES256_GCM,data:Qan6bDGeNbUGrVQGsh7urlp1waHy1eMG1jEjeqKYRm/5+QKRwluwEK/JLI8nWbIZl8rKHtKWxcSYydH1609TYLD/7y59,iv:D9c6lokwA5Gw6PKIDsuUPzH1ecFIM8rGxTC8uowLC78=,tag:QBDNj3wQISdPfoNnIJuOOw==,type:str]
                - name: ENC[AES256_GCM,data:QiIzIQAHpxQh6tDqB/l9,iv:nu0HfynHRXh2txhalyzO4c8x+uX8pkZdBAp1gdAUpHI=,tag:9vFu7neZ0e7gSynFu8pBpA==,type:str]
                  webhook_configs:
                    - url: ENC[AES256_GCM,data:4o6mKxA4yjOflvABFQc9BiXw02EUB5jXb6MX9oaxL5GSyhblFQI80PsyC15y34G2OzH1YK4+IVUqfQQu/LxXCPX6H1UQ6puMsCeDEqrpiQTPvgcPBvLifij7sv3SUtDXKVZWZNIBCi7lAs6Jd0WUD8k9tW6Wf1ZUhQGVzD8=,iv:tPY1rGZbjg9zuVRkiL5FkoxrEuUAGYHiPt6GT/MBS5U=,tag:xffPm/fLvMl+NM5m77GUSw==,type:str]
                      send_resolved: ENC[AES256_GCM,data:sCdUxpw=,iv:Fxru0LX+j8B5R5dIi7WKw/Z3Jk94Z93GBFHvbBw2lnc=,tag:1uyh7mUTBzGiX/q0A2DJ6w==,type:bool]
    openshift:
        username: ENC[AES256_GCM,data:udxawhzVghg=,iv:Wm2VN2/dMKh8l6PuqX+RbF2pzxPNk3dVyjJtSDkfu/8=,tag:kP1WxdkCYmczylNZHh3vvA==,type:str]
        password: ENC[AES256_GCM,data:NDEFO1MoieADYhXdYDKtCiWqYLbaug7joKTTqwNwCkeB+hZr,iv:kqvKfFLeM8/M3th9mhw2vnA4E/wC3CKWNzqnAwibOjE=,tag:J6yH4T9UzP1wc3IId07AIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-25T09:22:59Z"
    mac: ENC[AES256_GCM,data:xaOGuruCC8sxF5lRAbo/fS4ENjJDOk9d9st3zv9AvwFMZ99CiBXaimNG+AtY0MaNk5/mA/R0hJVMXnMptp+DpW3nzVu55mNZayPvytIOyMc3Y63foN9V6ZQNyWfVGlIkvSwypiz+RERzPv6t18MuIJ9ZILYWlwjgH790hyC/S60=,iv:hxflQmDwMKGKJUis62koEC9el/fo05WODJW7hwN+LmU=,tag:ausjYABwv1g5qiqPiB7dKw==,type:str]
    pgp:
        - created_at: "2022-08-25T09:22:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D8ii6b8ZY7xMSAQdAibWoP6hxlCcYziPPsxW5TKFvRHazqFgsUZ8zemdnIyMw
            HOWOdD8d4YmNCb0LEVEKpbF4x7Rtr1NpcViPZPMx21Jxx2GIrggZ4TuZq7R3jiS4
            0l4BqvHSw0H5k97Pm7hJUOF0L/kZFkQk9WhxcDUJetJvJUusvSpHprZSJKx0uRby
            BBnZw9ImntDDfFY8vRHKXwD8pPFiy768JWPhkVZ2egJOcUajXHAbbMG9nS3zoPzi
            =h5Fi
            -----END PGP MESSAGE-----
          fp: AA13F9CA4C303D151079DB58A0DDC3025026FBFF
    unencrypted_suffix: _unencrypted
    version: 3.7.3
