apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fluentbit-tls
spec:
  commonName: fluentbit-client
  secretName: fluentbit-tls-secret
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS8
  issuerRef:
    name: logging-operator-ca-issuer
    kind: Issuer
    group: cert-manager.io
