apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logging-operator-logging-fluentd-anyuid
  namespace: logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: logging-operator-logging-fluentd
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logging-operator-logging-fluentbit-priv
  namespace: logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: logging-operator-logging-fluentbit
  namespace: logging
