grafana:
    adminPassword: ENC[AES256_GCM,data:V4ojJTw+DIl49EA1gW13bw==,iv:xfvnRQYa4tMbwRLk8x9+ZphUrk+yGxoxAl//uWI8fN4=,tag:9K/7KzL9ZEtYbrCGXgAkDA==,type:str]
    adminUser: ENC[AES256_GCM,data:srTbyU3uso+xsRrB,iv:YUWHDTla0dFuH0nEjkm+DnBadIpPJkOoVeCM4swquvU=,tag:98F4i7oGPaWZBhsfi/nL8Q==,type:str]
    grafana.ini:
        auth.github:
            enabled: ENC[AES256_GCM,data:5iVT0A==,iv:JVc4iCExkWDPd83Sw+e9uRnyHLu3HvRjBRYYlWl1d9g=,tag:B+ljBz3kMYrBn1YfI7H5WQ==,type:bool]
            client_id: ENC[AES256_GCM,data:N0d9/yIx6AVwRZBZSOkkj8/FgfU=,iv:ORVANK99syJe648V0b9Agk9J9T36gfyUDhpYBUY4KqY=,tag:+SGJbvYVfqMbf80fZmw+ZA==,type:str]
            client_secret: ENC[AES256_GCM,data:15r6xzgmbfD7FJD9gqcYUonpWH7Vk42GexzeUjw4Y2n99uqOvM3P2A==,iv:l4EqDJMySgMrwZ17wcX4WomkPQzxUVz7XE/fXR646p8=,tag:eNG1yIlrG5wxWSrlvKWeZg==,type:str]
            scopes: ENC[AES256_GCM,data:bQFl0cS3y/d2nmbxMn2l4SAnCg==,iv:j5wDbeCpNX3fJ5LuM566+y5T5ZRRjkFRrSF8BsDog/Y=,tag:raCjLcw/ZozMxjsCtBtKAQ==,type:str]
            auth_url: ENC[AES256_GCM,data:n/gwn0C7GXLYHr5xYiYBdhPgAMi4sElHVNOFtjMfJpWiKkIqGZziLg==,iv:P5F2QrfvqE6LnCo2yKqHo7onTgNhyHq3B8PiSIxcHXY=,tag:lhH+WZ9GDD+C7syfXfO0lA==,type:str]
            token_url: ENC[AES256_GCM,data:VaOXP2Unu9gqxWVq2dKmavAr4GZS0oVk/3JKC8TbPyOj4YFKkkewYIZc4A==,iv:uzWKHrqoMBGHo0JYeu0fT7zBu/t4Py4rWKLIBpU4DiI=,tag:r3uA+VkSs8R9GAzlsr7jzA==,type:str]
            api_url: ENC[AES256_GCM,data:xpfMisPCgnl9D96DtC991sBi8UWLjFA5hCrq,iv:euq1oCm1FmTvfQEZhSmCkjWJ1NAld4sQ/AtYwvVnzi0=,tag:peNWsL7Cdtr0kaxDILltJQ==,type:str]
            allow_sign_up: ENC[AES256_GCM,data:6zXwjg==,iv:E0Htk5YejkXV62satVQs1Jxte6Zh5M804wJEcdGpfnw=,tag:QS4YnFpgu66gGQzQx5qI3g==,type:bool]
            #ENC[AES256_GCM,data:DMYXTqcCbho6eL2J86gtW+OzRNZid7oJOtpk2HANKX0Rz6A=,iv:hWc8AR0blZujlsMjXZB7E5uKE/W7WrQkp/eYbRKTm5k=,tag:BG2LX8JNhcGQYfwmfcYmTQ==,type:comment]
            allowed_organizations: ENC[AES256_GCM,data:nv6kqqxBz2eD6ZsoM9I=,iv:26MDu5alo+NQw5bXFd3vVff6XrB/bfQTMx6PK9YvdWA=,tag:6n3OOsnKBAgC96G0+rwt2g==,type:str]
oncall:
    mariadb:
        auth:
            rootPassword: ENC[AES256_GCM,data:RYCBA12E2lebcA==,iv:JPpHKIyViV4IcgwZ3aLdZh8fOkNZAXzFbPVtVhSmj3c=,tag:es0G5ewyuTbjWp2mtcZxbA==,type:str]
            database: ENC[AES256_GCM,data:DCxnj6Jp,iv:BWP720jLgT5QfRoW3dckiWWXA/ffJIy0PZsHR5BPJGI=,tag:Z+uOIxY5tQYUmjO0oDwv4Q==,type:str]
    rabbitmq:
        auth:
            username: ENC[AES256_GCM,data:e/4alA==,iv:6l4zBBu3XyyE1C/lneI6WRZNWpSqCAaR6jJtYxwxJS4=,tag:f5TFhNrHuU6RQH/da3b6TQ==,type:str]
            password: ENC[AES256_GCM,data:H+pD4F3Xg3QpxGvTmf5qnA==,iv:O8FCTBP7vQm5dl8y57JN5p8ELL5WvPYdqCXta2Mc29M=,tag:ZSOzIYllH8dWJ9VvbSBKhg==,type:str]
            erlangCookie: ENC[AES256_GCM,data:zTHYquDtoOj3f2/ZXGM2po7CqCTqYW2VvWilc6p9Hlk=,iv:HW4lo9nufKak2DrzrMSS/tRIM/k/f369EdKb37BOIs0=,tag:NRwMestZcxlVyB2x1tuj3g==,type:str]
    redis:
        auth:
            password: ENC[AES256_GCM,data:+U+L4S0erA8RkA==,iv:/WqcopUz/EwiVnhAzbfMvHBme64/hSDAA6GCnwmYMJI=,tag:p96Gu1EPPI6qUi+dVmNpcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-24T11:32:52Z"
    mac: ENC[AES256_GCM,data:EOSI+H4XgHy9zx12Ho7tsGa3gqQChtP1Y2EAkaAOqX7sHDS/44oQeHH83bnAYBvdjgSOCi7uxAENSdczgdwktkPy25LMbu4ymMyr2fOGwxUZlGtl8x/Yz6NiO9qeBAmb1rsWeI1zqshSN8fUhHy3dcRqI4CtEPa8RUnyQOuWkhc=,iv:xK9LCrQXG5DYJlk5muFV/Y5WOuvMjm+cuYPYHIrEzSg=,tag:qQHq2LssRFG8ncUKmlaNXg==,type:str]
    pgp:
        - created_at: "2022-08-24T11:32:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D8ii6b8ZY7xMSAQdA9n+QApKApdhMXX2KBOwyLZenBl//p5swzF9Zj9YWF3kw
            WDUdHvigUzWQTQDqObN5aWed+di0JxoumeRAi4wFbd674XHcaXO5DBa647rvr7rJ
            0lwBIyrN7xFZuUEvWj97284CH9NlxMQ6zgLzl4xjK1wzHQKLEoR/MWX3OWsJy2bz
            ohMKO8VRhKMh1xXOEG81uvor9it2bi1ej5745GZ410wSp7EzKYsiW5IhVs8DdQ==
            =a4ht
            -----END PGP MESSAGE-----
          fp: AA13F9CA4C303D151079DB58A0DDC3025026FBFF
    unencrypted_suffix: _unencrypted
    version: 3.7.3
