grafana:
    adminPassword: ENC[AES256_GCM,data:xQ47yfgeafyajsmKRJpVMQ==,iv:DFKONsf+KnzhzPEJpOJccTeXHLsRn6rEBxACI7KFLS0=,tag:GN8peELQvD0/AzPUU/elkg==,type:str]
    adminUser: ENC[AES256_GCM,data:NDs8da4R10qbP2Tr,iv:GKeDDB/96D3VrD0RqiSBvXYuqrNm2Rh5zb3koTFY+Ig=,tag:vgYOVPbkE1HzNrvwvk5mgw==,type:str]
    grafana.ini:
        auth.github:
            enabled: ENC[AES256_GCM,data:SX8/zw==,iv:SJqFyzVKAPez9ZnX6xv2pZY1AnLiVUH+xNqCLlRATmQ=,tag:jwPdBP7PS1tb7zUM9kseAg==,type:bool]
            client_id: ENC[AES256_GCM,data:QK6NArfyZy4ahU2r0V8yzHmxaCE=,iv:QE/KQdLJ2ttp75TEBBmIz/HJToY7XrMj/wSZLIHQEbw=,tag:SR+AgXW0G4wCQocNKeMkcQ==,type:str]
            client_secret: ENC[AES256_GCM,data:9KHVfeUayw/Rd7qnwxCedJm2RYwa9SDqOcEB1prfBRBY9ySiH1F5Sg==,iv:kE1FXp15dY9rKlT4p6BBM6mSRrqABskrv7+O/1phhMY=,tag:VMnETGLSosFktVclpbuAdA==,type:str]
            scopes: ENC[AES256_GCM,data:z26eDV5hqykluAOcYwUr0Y+SbA==,iv:e/BsredhJ6YhLEKOivjcRvECZBLRVFLOgimQ/Kgn92A=,tag:1V1aoTKsdOTPt/U+EohgWA==,type:str]
            auth_url: ENC[AES256_GCM,data:6u4zxWFv8YFheQiTyO0VIDb1N8E99BUMx59117JYJ1C9zP4atWdrhw==,iv:eGG0RLAk40Jf/Vtzy4qg0geN2BKtIM9mbz6OI2CfTag=,tag:kgNtPuk/IvQONK7ODK6jUA==,type:str]
            token_url: ENC[AES256_GCM,data:B0MBuh0cEQyAA0eEv1YMfQVokuWfwd5TLvGHu/TjG0gk0P90Acs/+NvOCg==,iv:yOtPgsBocNrhaw5WUzIe0JWAP9AnlWVZxKOAkwuSCvE=,tag:V7t0wfNK0Z4kHsY3pYY5SQ==,type:str]
            api_url: ENC[AES256_GCM,data:cWoAP2XOadlomEOgL1tGyTNtUNG3NJy0LgdR,iv:6MRnQ6O3X1L/tofVvMR9f9XanR5LRfhfdyzGlOFCAVU=,tag:ulzs/ccRQyP3cS2lIge+pA==,type:str]
            allow_sign_up: ENC[AES256_GCM,data:IBVGVA==,iv:hLCWIq7k4UuW0S80uVsWqx1KeERJrL3MD7cAvmxEUy4=,tag:V+0QUKLacuEO4eJvYN9nKw==,type:bool]
            #ENC[AES256_GCM,data:U9WiAA3a1avzaRfyDxHx+dxOMt9tIk+jSUESO+oqNqA+l2M=,iv:OdNm0WCgleTKrh+2sCgncRKXmRceq5L/w048AuV9VxE=,tag:nFmyiZWHaQr3WZswvoBkaQ==,type:comment]
            allowed_organizations: ENC[AES256_GCM,data:66iiOpeHhwj3EWx2yd4=,iv:L2x1uLCO7ttFJEzvbgd0gXmtDAlB/Bf4U+ab7F4O0D4=,tag:sbNTc2OJR2HBmIvdUFE6xw==,type:str]
        auth.jwt:
            enabled: ENC[AES256_GCM,data:P+is+w==,iv:kE8x9iYipHD3kJuZe0a12zwhKpJ7gidEVlgDSsUO6S4=,tag:V33I0GV8hOomgW195LVsxg==,type:bool]
            header_name: ENC[AES256_GCM,data:4IKychqkX9jTmk0bceRuM3/QENst6g==,iv:E88I1IjQYc0Ko3I0N+I5p/8xszakaJ3y9En2EA5GAjE=,tag:EBZr2RriAyMO5lw8XwsGJg==,type:str]
            email_claim: ENC[AES256_GCM,data:I8IV,iv:ASEjd/U06bjxYLIRYtLTrK0f9FPRZN7JlLGsI3GHmdI=,tag:e0LYvAzA41WTSymYaaHBAQ==,type:str]
            username_claim: ENC[AES256_GCM,data:pPJv,iv:3QSbg+CO9XGTn5bJ+KOclk0lPbuGMmKmqtTuuzcqHGw=,tag:kiG97YarPiXBpOdesTxrlQ==,type:str]
            auto_sign_up: ENC[AES256_GCM,data:Qo5Uyw==,iv:hkLDFiSty1G6c9pC/a3h58VXxVGboiGMClQNHLPqRfw=,tag:HGcVU5Wa/X9kI7aVGQzP0Q==,type:bool]
            jwk_set_url: ENC[AES256_GCM,data:OoHAIljkXbMxrEVctX9VOyDDjs+ho1asF3sduFFZDikGxZFS++Z2H1ilofv+Kde1PB8mUqE=,iv:2A0033pfnCM9eMS/SoVaCe9mZ5yxYQ5NqmsxuOb7IUc=,tag:vU0ti9GjVBVs22ClqYO2bA==,type:str]
oncall:
    mariadb:
        auth:
            rootPassword: ENC[AES256_GCM,data:HZgPJ2NWfikU9w==,iv:taRKvW3HUvGEa8Dd/K/ep23Efz3WmikxEx+MWxQfd1g=,tag:igAEjK1w3w8W//GqS8AAEg==,type:str]
            database: ENC[AES256_GCM,data:DyygxH4H,iv:ji+4LUNq5/dIlJ6oCRvEuGiwTDlR2clGi/fSacjOWlM=,tag:+Y8ZPILay7l6UOvoPfjKvQ==,type:str]
    rabbitmq:
        auth:
            username: ENC[AES256_GCM,data:hWsNZQ==,iv:o9fqdTdfvcq6jynT1SBcML1wVYXizznbwSwOENRJu3g=,tag:+/tmnlYNq/FiRfl6JzTIzw==,type:str]
            password: ENC[AES256_GCM,data:YM8GLvmfHoBBbGiJb3Vm9Q==,iv:ppmIr6JdoWoPiY3UthubelWIFoxbvBcpr3a9mlHviUA=,tag:fEn1ol6c1D+WTyamTyX77Q==,type:str]
            erlangCookie: ENC[AES256_GCM,data:sSHMqTo+wmy66Gh0MS6u3ngxctOO5/CkD0zLoCcTk7k=,iv:2PUpZ/MraGYJGxyv/UbQadzfCMxc2aZmANutsLqqJ90=,tag:snsjdHMSZFu1GVonQJKhbw==,type:str]
    redis:
        auth:
            password: ENC[AES256_GCM,data:3sqyHDvmIZ71xQ==,iv:cdpIRwD9uIdMtdax7UhVircTJWEW4LLxuWFVmGQVNn4=,tag:9Erz7K00r0CBFS28OjEqkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-05T04:51:28Z"
    mac: ENC[AES256_GCM,data:MElSU1GWdgC1MZmIWuK++k84x28jWIkoIzOv4Ccd2m0TvG66ezLPYaHzGM7MPTBFCPXiM2Nmv+Rxr3q6B9DRm7OJgZqTD3gVrfEne52qUSKuaxTR5GeiKj3ZRr3pmPmb7aSIMCRQ939cXWRutjmCQmfEjAbfrUk1A/ZLt8tfeIw=,iv:Eh0deMGdWm1irYCNXGBV02OW/YMzTvpiFOq3EfAgRf8=,tag:0aJH88qqXJ0StqW4yrT4/w==,type:str]
    pgp:
        - created_at: "2022-09-05T04:51:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D8ii6b8ZY7xMSAQdAHwTw3d7aJhCWsd53Uz0Pc1y3+oQSAlZ22hdrh5Jz5FUw
            7nznFgXhhEQeskPjLOS2xemGuuQjdE0pFXbRNHOIHswJb6ItmO23eUNjW32jamrk
            0lwBnRoOdJt7AFQyJ+HRhMfSY9AbNm4wO4tCtHIvE5PfvvTQhKZwHdHINInGtxH0
            gzGv72EOeRwVMLTNQ1YR7nC9o8isIzyS79TTlJSgOgc3jXR+iUZikuyLVUqe+A==
            =QoIH
            -----END PGP MESSAGE-----
          fp: AA13F9CA4C303D151079DB58A0DDC3025026FBFF
    unencrypted_suffix: _unencrypted
    version: 3.7.3
