---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oc-iac-manual
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - git:
      repoURL: git@github.com:ForomePlatform/oc-iac.git
      revision: HEAD
      files:
      - path: helm/**/manual.yaml
  template:
    metadata:
      name: '{{include "cc" $ }}path[1]}}'
    spec:
      project: 'default'
      source:
        helm:
          valueFiles:
          - values.yaml
          - "secrets+gpg-import:///helm-secrets-private-keys/key.asc?secrets.yaml"
        repoURL: git@github.com:ForomePlatform/oc-iac.git
        targetRevision: HEAD
        path: '{{include "cc" $ }}path}}../'
      destination:
        server: '{{include "cc" $ }}cluster.address }}'
        namespace: '{{include "cc" $ }}path[1]}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oc-iac-auto
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - git:
      repoURL: git@github.com:ForomePlatform/oc-iac.git
      revision: HEAD
      files:
      - path: helm/**/auto.yaml
  template:
    metadata:
      name: '{{include "cc" $ }}path[1]}}'
    spec:
      project: 'default'
      source:
        helm:
          valueFiles:
          - values.yaml
          - "secrets+gpg-import:///helm-secrets-private-keys/key.asc?secrets.yaml"
        repoURL: git@github.com:ForomePlatform/oc-iac.git
        targetRevision: HEAD
        path: '{{include "cc" $ }}path}}../'
      destination:
        server: '{{include "cc" $ }}cluster.address }}'
        namespace: '{{include "cc" $ }}path[1]}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 10
