kind: app
version: v3
metadata:
  name: anfisa-dev
  description: "Forome anfisa dev"
  labels:
    hostname: openshift
    qa: access
    front: access
    developers: access
spec:
  uri: "https://anfisa.forome.dev"
  # public_addr: "anfisa.forome.dev"
  rewrite:
    redirect:
      - "anfisa.forome.dev"
    headers:
      - Name: Host
        Value: anfisa.forome.dev
  insecure_skip_verify: true
