kind: app
version: v3
metadata:
  name: anfisa-dev
  description: "Forome anfisa dev"
  labels:
    hostname: dev
    qa: access
    front: access
    developers: access
spec:
  uri: "http://localhost:3042"
  # public_addr: "anfisa.forome.dev"
  rewrite:
    redirect:
      - "localhost"
  insecure_skip_verify: true
---
kind: app
version: v3
metadata:
  name: anfisa-dev-druid
  description: "Forome anfisa dev-druid"
  labels:
    hostname: dev
    qa: access
    front: access
    developers: access
spec:
  uri: "http://localhost:8888"
  public_addr: anfisa-dev-druid.teleport.forome.dev
  rewrite:
    redirect:
      - "anfisa-dev-druid.teleport.forome.dev"
    headers:
      - Name: Host
        Value: anfisa-dev-druid.teleport.forome.dev
  insecure_skip_verify: true
