kind: app
version: v3
metadata:
  name: loki
  description: "Forome loki"
  labels:
    hostname: openshift
    admins: access
spec:
  uri: "http://loki.loki.svc.cluster.local:3100"
  insecure_skip_verify: true
