kind: app
version: v3
metadata:
  name: mongodb-qa
  description: "mongodb Forome anfisa qa"
  labels:
    qa: access
    front: access
    developers: access
    hostname: openshift
spec:
  uri: "tcp://anfisa-mongodb.anfisa-qa.svc.cluster.local:27017"
---
kind: app
version: v3
metadata:
  name: mongodb-test
  description: "mongodb Forome anfisa test"
  labels:
    qa: access
    front: access
    developers: access
    hostname: openshift
spec:
  uri: "tcp://anfisa-mongodb.anfisa-test.svc.cluster.local:27017"

---
kind: app
version: v3
metadata:
  name: mongodb-port
  description: "mongodb Forome anfisa port"
  labels:
    qa: access
    front: access
    developers: access
    hostname: openshift
spec:
  uri: "tcp://anfisa-mongodb.anfisa-port.svc.cluster.local:27017"

---
kind: app
version: v3
metadata:
  name: mongodb-dev
  description: "mongodb Forome anfisa dev"
  labels:
    qa: access
    front: access
    developers: access
    hostname: dev
spec:
  uri: "tcp://localhost:27017"
---
kind: app
version: v3
metadata:
  name: mongodb-demo
  description: "mongodb Forome anfisa demo"
  labels:
    hostname: demo
spec:
  uri: "tcp://localhost:27017"
