kind: app
version: v3
metadata:
  name: anfisa-port
  description: "Forome anfisa port"
  labels:
    hostname: openshift
    qa: access
    front: access
    developers: access
spec:
  uri: "https://port.forome.dev"
  public_addr: port.forome.dev
  rewrite:
    redirect:
      - "port.forome.dev"
    headers:
      - Name: Host
        Value: port.forome.dev
  insecure_skip_verify: true
---
kind: app
version: v3
metadata:
  name: anfisa-port-druid
  description: "Forome anfisa port-druid"
  labels:
    hostname: openshift
    qa: access
    front: access
    developers: access
spec:
  uri: "http://router.anfisa-.svc.cluster.local"
  public_addr: anfisa-port-druid.teleport.forome.dev
  rewrite:
    redirect:
      - "anfisa-port-druid.teleport.forome.dev"
    headers:
      - Name: Host
        Value: anfisa-port-druid.teleport.forome.dev
  insecure_skip_verify: true
