kind: app
version: v3
metadata:
  name: anfisa-scicenter
  description: "Forome anfisa scicenter"
  labels:
    hostname: dev-scicenter
    qa: access
    front: access
    developers: access
spec:
  uri: "http://localhost:3005"
  # public_addr: "anfisa.forome.dev"
  rewrite:
    redirect:
      - "localhost"
  insecure_skip_verify: true
