kind: app
version: v3
metadata:
  name: anfisa-scicenter
  description: "Forome anfisa scicenter"
  labels:
    hostname: dev-scicenter
    qa: access
    front: access
    developers: access
spec:
  uri: "http://localhost:3005"
  # public_addr: "anfisa.forome.dev"
  rewrite:
    redirect:
      - "localhost"
  insecure_skip_verify: true
---
kind: app
version: v3
metadata:
  name: anfisa-scicenter-druid
  description: "Forome anfisa scicenter-druid"
  labels:
    hostname: openshift
    qa: access
    front: access
    developers: access
spec:
  uri: "http://router.anfisa-.svc.cluster.local"
  public_addr: anfisa-scicenter-druid.teleport.forome.dev
  rewrite:
    redirect:
      - "anfisa-scicenter-druid.teleport.forome.dev"
    headers:
      - Name: Host
        Value: anfisa-scicenter-druid.teleport.forome.dev
  insecure_skip_verify: true
