# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: collector-metrics
spec:
  commonName: "cluster-logging-operator-metrics"
  dnsNames:
  - cluster-logging-operator-metrics
  duration: 8760h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  renewBefore: 4380h0m0s
  secretName: collector-metrics
  subject:
    organizations:
    - gis.local
  usages:
  - signing
  - key encipherment
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
