apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: remoteloki
      type: loki
      url: 'http://loki.loki.svc.cluster.local:3100'
  inputs:
    - name: anfisa
      application:
          namespaces:
          - anfisa-port
          - anfisa-qa
          - anfisa-test
  pipelines:
    - name: anfisa
      inputRefs:
        - anfisa
      outputRefs:
        - remoteloki
