apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: forome-prometheus
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: forome-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 39.6.0
    argocd.argoproj.io/instance: forome-prometheus
    chart: kube-prometheus-stack-39.6.0
    heritage: Helm
    release: forome-prometheus
  name: prometheus-kube-prometheus-prometheus
  namespace: forome-prometheus
spec:
  endpoints:
  - path: /metrics
    port: http-web
  namespaceSelector:
    matchNames:
    - forome-prometheus
  selector:
    matchLabels:
      app: kube-prometheus-stack-prometheus
      release: forome-prometheus
      self-monitor: "true"
