# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
stringData:
  password: {{ .Values.prom.password }}
  username: {{ .Values.prom.username }}
kind: Secret
metadata:
  name: forome-prometheus-auth
type: Opaque
---
apiVersion: v1
stringData:
  basicauth: {{.Values.forome.username}}:{{.Values.forome.password}}
kind: Secret
metadata:
  name: forome-basic-auth
type: Opaque
