
loki:
  config:
    # existingSecret:
    auth_enabled: false

    memberlist:
      join_members:
        # the value must be defined as string to be evaluated when secret manifest is being generating
        - '{{ include "loki.fullname" . }}-memberlist'

    ingester:
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 1m
      max_transfer_retries: 0
      wal:
        dir: /data/loki/wal
      lifecycler:
        ring:
          replication_factor: 1

        ## Different ring configs can be used. E.g. Consul
        # ring:
        #   store: consul
        #   replication_factor: 1
        #   consul:
        #     host: "consul:8500"
        #     prefix: ""
        #     http_client_timeout: "20s"
        #     consistent_reads: true
    limits_config:
      reject_old_samples: true
      max_entries_limit_per_query: 5000
      enforce_metric_name: false
      reject_old_samples_max_age: 24h
      max_query_length: 100h
      max_streams_per_user: 0
      max_global_streams_per_user: 0
      ingestion_rate_strategy: 'global'
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_cache_freshness_per_query: 20m
      split_queries_by_interval: 60m
      retention_period: 100h
    schema_config:
      configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      grpc_server_max_recv_msg_size: 20971520
      grpc_server_max_send_msg_size: 20971520
      grpc_server_max_concurrent_streams: 0
      http_server_write_timeout: 1m
      grpc_server_min_time_between_pings: '10s'
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 100h
    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: filesystem

  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 10Gi
    storageClassName:

  rbac:
    create: true
    pspEnabled: true

  replicas: 1

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi

  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001

  containerSecurityContext:
    readOnlyRootFilesystem: true

  service:
    type: ClusterIP
    nodePort:
    port: 3100
    annotations: {}
    labels: {}
    targetPort: http-metrics

  serviceAccount:
    create: true
    name:
    annotations: {}
    automountServiceAccountToken: true

  updateStrategy:
    type: RollingUpdate

promtail:
  enabled: false
  config:
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
