# Source: teleport-cluster/charts/teleport-cluster/templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
spec:
  secretName: teleport-tls
  commonName: "teleport.forome.dev"
  dnsNames:
  - "teleport.forome.dev"
  - "grafana.teleport.forome.dev"
  - "anfisa-demo.teleport.forome.dev"
  - "anfisa-dev.teleport.forome.dev"
  - "anfisa-qa.teleport.forome.dev"
  - "anfisa-port.teleport.forome.dev"
  - "anfisa-scicenter.teleport.forome.dev"
  - "mllogs.teleport.forome.dev"
  - "argocd.teleport.forome.dev"
  - "qa.teleport.forome.dev"
  - "test.teleport.forome.dev"
  - "dev.teleport.forome.dev"
  - "demo.teleport.forome.dev"
  issuerRef:
    name: clusterissuer-prom
    kind: ClusterIssuer
    group: cert-manager.io
