{{- $backendProtocol := ternary "ssl" "tcp" (hasKey .Values.annotations.service "service.beta.kubernetes.io/aws-load-balancer-ssl-cert") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  {{- if (or (.Values.annotations.service) (eq .Values.chartMode "aws")) }}
  annotations:
    {{- if eq .Values.chartMode "aws" }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: {{ $backendProtocol }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- end }}
    {{- if .Values.annotations.service }}
      {{- toYaml .Values.annotations.service | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ default "LoadBalancer" .Values.service.type }}
  {{- with .Values.service.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  ports:
  - name: https
    port: 443
    targetPort: 3080
    protocol: TCP
  {{- if not .Values.proxyListenerMode }}
  - name: sshproxy
    port: 3023
    targetPort: 3023
    protocol: TCP
  - name: k8s
    port: 3026
    targetPort: 3026
    protocol: TCP
  - name: sshtun
    port: 3024
    targetPort: 3024
    protocol: TCP
  - name: mysql
    port: 3036
    targetPort: 3036
    protocol: TCP
  {{- if .Values.separatePostgresListener }}
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  {{- end }}
  {{- if .Values.separateMongoListener }}
  - name: mongo
    port: 27017
    targetPort: 27017
    protocol: TCP
  {{- end }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}
